### ISSUE TITLE
ShowedItemsVisibility.onType isn't showing any options

### ISSUE THREAD

**Issue by tinashepb** [esentis/multiple_search_selection#13]
When the ShowedItemsVisibility is set to onType, nothing appears when you start typing. Not sure if there's other configuration  options I'm supposed to change for it to work. 

Please could you kindly assist.

**Comment by esentis** [comment]
Hello there and thanks for taking the time to fill the issue.

I just checked the issue and indeed there seems to be a bug, I have fixed it and will send a new update `2.2.1` with the fix.

**Comment by tinashepb** [comment]
Thank you much appreciated.

**Comment by tinashepb** [comment]
Thank you, much appreciated
