### ISSUE TITLE
Reseting search text field on item added

### ISSUE THREAD

**Issue by tinashepb** [esentis/multiple_search_selection#15]
Hi. 

Sorry I'm not sure if this is already available but is there a way to reset the search text field once the user has made a selection?

Regards

**Comment by esentis** [comment]
Hello there again:) Nope there is no such feature yet, I could add a flag on next release e.g 'resetSearchOnSelect' which will default to 'false' and can do the trick you want :)

**Comment by esentis** [comment]
Added a flag `clearSearchFieldOnSelect` wich defaults to `false`. Suit yourself :)

**Comment by tinashepb** [comment]
Thank you so much.
