### ISSUE TITLE
Case sensitivity in search is broken

### ISSUE THREAD

**Issue by anqit** [esentis/multiple_search_selection#19]
Want to start by saying this is a great widget, it was the only one I could find that met all of my criteria, thanks!

## Current Behavior

When searching using capital letters, items who `fieldToCheck` contains that capital letter are not returned.

For example, if I was searching for some `User` object that had a `name` field and `fieldToCheck` was `(u) => u.name`, I had a user whose name value was `Anqit`, and I searched for `A`, `Anqit` is not returned, however if I search for `a`, it is.

I believe it is because of lines like `(item) => widget.fieldToCheck(item).toLowerCase().contains(_textEditingController.text)`. Here, the value returned from `fieldToCheck` is converted to lower case, but the text value from the controller is not. 

## Expected behavior/code

I would expect searching using capital letters should return items whose `fieldToCheck` values contains those capital letters.

### Environment
Don't think this is relevant

### Possible Solution
A quick fix would be to also convert the text field value to lower-case in all of the places the search is done:
`(item) => widget.fieldToCheck(item).toLowerCase().contains(_textEditingController.text.toLowerCase())`
A cool feature might be being able to provide a custom search function, maybe something that takes the text field value and returns a custom list of items. Or perhaps have the case sensitivity configurable (and working ;) )

**Comment by anqit** [comment]
I think it would also be generally preferable if the fuzzy search algorithms were also case-insensitive, or at least configurable to be

**Comment by anqit** [comment]
took a stab at it

**Comment by esentis** [comment]
Hello there ! Thanks for taking the time to use and find the issue and of course making a PR ❤️ I'll look into it asap and get back at you.

**Comment by esentis** [comment]
Closed from #20
