### ISSUE TITLE
Customize pickedItems display

### ISSUE THREAD

**Issue by anqit** [esentis/multiple_search_selection#23]
I think it would be neat to be able to customize certain aspects of the display. In particular, I would like to provide a custom widget to show the picked items.

**Comment by esentis** [comment]
Interesting, so you would like to provide your own `Widget` that will accomodate the `pickedItemBuilder`, can you give me a visual or code example ?

**Comment by anqit** [comment]
I don't have a visual yet, but I'd like to show the picked users in a single, horizontally scrolling `ListView`, which I don't think is possible at the moment? I could be wrong though. I don't mind taking a stab at a PR for it myself when I get a chance to do so

**Comment by esentis** [comment]
Cool, I'll look into it if I can expose the picked items container, in a builder function. You're right currently this is not available.

**Comment by esentis** [comment]
Ok I think we are done here, I have added a new parameter `pickedItemsContainerBuilder` you can see below an example with the outcome.

```dart
pickedItemsContainerBuilder: (pickedItems) => Center(
    child: Container(
    height: 150,
    width: 150,
    decoration: BoxDecoration(
        border: Border.all(color: Colors.grey[400]!),
      ),
    child: ListView(
        children: pickedItems,
    ),
  ),
),
pickedItemBuilder: (country) {
    return Padding(
    padding: const EdgeInsets.all(8),
    child: Center(
        child: Text(
        country.name,
        style: const TextStyle(
            color: Colors.blue,
            decoration: TextDecoration.underline,
        ),
      ),
    ),
  );
},
```

<img src="https://i.imgur.com/EXZvBr0.gif" title="pickedItemsBuilder" />

**Comment by anqit** [comment]
Looks great, thanks for the quick update!
