### ISSUE TITLE
Limit how many items can be selected

### ISSUE THREAD

**Issue by lokesh-gam** [esentis/multiple_search_selection#32]
Hi
How to disable the multiple selection. ?

**Comment by esentis** [comment]
Hello and thanks for openning the issue ! Can you please elaborate what you mean by disabling ? Disable the textfield to prevent typing or.. ?

**Comment by lokesh-gam** [comment]
I need to disable multiple selection option, user should have the option to select only one item from the search list.

**Comment by esentis** [comment]
So after selecting one item, you want to prevent the user from typing or from selecting a new item from the list?

**Comment by lokesh-gam** [comment]
Yeah, If user selected one item, he/she wanted to select other one, Then it should remove old one and only show the new one.

**Comment by esentis** [comment]
Interesting, I will add it as a feature with the next release wait for the updates ;)

**Comment by lokesh-gam** [comment]
Thank you 👍 @esentis , waiting for this feature.
