### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by SUNbrightness** [esentis/multiple_search_selection#33]
when I run the example project in multiple_search_selection.
if I click Select All button, the error will happen.

Flutter 3.7.12 • channel stable • https://gitee.com/mirrors/Flutter.git  
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by esentis** [comment]
@SUNbrightness Hello there and thanks for reporting the issue ! There was a tiny bug that is already fixed and released with 2.5.1.
