### ISSUE TITLE
itemsVisibility: ShowedItemsVisibility.onType when created a new item it's disable

### ISSUE THREAD

**Issue by SUNbrightness** [esentis/multiple_search_selection#34]
I am sorry I meet a new problem,
 I set this itemsVisibility: ShowedItemsVisibility.onType 
but the items still shows after created a new item,

**Comment by esentis** [comment]
Thanks for reporting the issue, I'll look at it and get back at you asap.

**Comment by SUNbrightness** [comment]
> Thanks for reporting the issue, I'll look at it and get back at you asap.

thanks you, you are diligent. I think I am lazy to solve this problem

**Comment by esentis** [comment]
@SUNbrightness Alright this is also resolved with 2.5.2 ! Thanks again for reporting it.
