### ISSUE TITLE
Optionally move pickedItemsContainer to bottom

### ISSUE THREAD

**Issue by akash-ramaswamy** [esentis/multiple_search_selection#39]
## Customize the position of the pickedItemsContainer

@esentis thanks for this flutter package. I had one usecase where I needed the picked items container to be bottom of the widget stack. So raising this PR for implementation of the specified feature.

<img width="500" alt="Screenshot 2023-11-19 at 10 35 15 AM" src="https://github.com/esentis/multiple_search_selection/assets/87078332/ec2cd3b3-dfb7-496b-a670-c5623ecc6fe3">

**Comment by esentis** [comment]
@akash-ramaswamy Hello there ! I'm glad you found use of the library. It's an interesting addition, thanks for the PR !
