### ISSUE TITLE
Ability to specify TextInputType

### ISSUE THREAD

**Issue by becjit** [esentis/multiple_search_selection#43]
## Current Behavior

As this is essentially a text input type , there should be an option to specify text input type. Looks like the current behavior default to TextInputType to text and there is no way to change it

## Expected behavior/code

Ability to specify textinputtype such as name, email etc

### Environment

- Operating System
- `flutter doctor -v`

### Possible Solution

`Only if you have suggestions on a fix for the bug`

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by esentis** [comment]
Yes ! It will be added on next release.
