### ISSUE TITLE
Error: Type 'OverlayPortalController' not found

### ISSUE THREAD

**Issue by tailn804** [esentis/multiple_search_selection#50]
## Current Behavior

When I install multiple_search_selection version 2.6.2 and assign the first line MultipleSearchController Controller = MultipleSearchController(); and save, detect errors as attached image.

## Expected behavior/code

A clear and concise description of what you expected to happen (or code).

### Environment

- Operating System
- `flutter doctor -v`

> [√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.7.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (1 year, 1 month ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\tailn\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.8.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34309.116
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\tailn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 121.0.6167.86
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 122.0.2365.59

[√] HTTP Host Availability
    • All required HTTP hosts are available

### Possible Solution

`Only if you have suggestions on a fix for the bug`

### Additional context/Screenshots
![Screenshot 2024-03-01 161213](https://github.com/esentis/multiple_search_selection/assets/104020709/1ef3f68b-d029-4ce1-ac1b-1d2c0c24767b)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by esentis** [comment]
@tailn804 Hello there and thanks for taking the time to fill the issue !!

Unfortunately, `OverlayPortal` was introduced with Flutter `3.10` and is not available for your current version.

**Comment by tailn804** [comment]
Thank you for your support, so which version of the package should I use for my flutter 3.7.3?

**Comment by esentis** [comment]
The `overlay` support was introduced with `2.6.0`, try `2.5.6` to see if it's resolved.

**Comment by tailn804** [comment]
There is no other way, thank you, I will upgrade flutter to 3.10
