### ISSUE TITLE
[Feature] Checkbox 

### ISSUE THREAD

**Issue by shinriyo** [esentis/multiple_search_selection#54]
## Is your feature request related to a problem?

checkbox
like this
https://dribbble.com/shots/4958808-Multi-select-dropdown-menu-with-search?utm_source=Pinterest_Shot&utm_campaign=matiagobbo&utm_content=Multi-select+dropdown+menu+with+search&utm_medium=Social_Share

## Describe the feature you'd like

I want to add checkbox when select.

## Describe alternatives you've considered

when select it is checked.
when unselect it is unchecked.

**Comment by esentis** [comment]
Hello there @shinriyo !
This is an interesting feature, a new constructor should be added...hmm will look into it and get back at you asap !

**Comment by esentis** [comment]
@shinriyo 
The changes you requested are now live with 2.7.0 ! 
Please read the [CHANGELOG](https://github.com/esentis/multiple_search_selection/blob/develop/CHANGELOG.md) to see how it works ;)

Cheers and enjoy
