### ISSUE TITLE
PickItem list is always empty

### ISSUE THREAD

**Issue by zionnite** [esentis/multiple_search_selection#55]
Hello sir, 
Thanks for this awesome package, but it's not working properly for me. Whenever I pick an item from the dropdown list, it always returns empty.

Please, how do I get the selected picked item?
thanks
I'm using the current version `multiple_search_selection: ^2.7.0`
![Screenshot 2024-10-24 at 10 52 39](https://github.com/user-attachments/assets/8e2d249c-bd1e-43f5-a47b-194cff35836e)

**Comment by esentis** [comment]
@zionnite hello fella, thanks for using the library <3 I'll look into it and get back at you !

**Comment by esentis** [comment]
@zionnite Can you give me a minimal reproducable code ? Because if you look at the [default example](https://github.com/esentis/multiple_search_selection/blob/develop/example/lib/examples/default_example.dart) and change the `onChanged` to 

```dart
          onItemAdded: (c) {
            print(c);
            print('All items length ${controller.getAllItems().length}');
            print('Picked items length ${controller.getPickedItems().length}');
          },
```

you will see it doesn't reproduce.

Can you share the code where you assign the `controller` maybe something happens to it.

**Comment by zionnite** [comment]
Thanks for your quick reply, 
I just checked your example again and I discovered, that you declare the `controller` inside the `build()` method I did declare mine above the `build()` method 


<img width="1440" alt="Screenshot 2024-10-24 at 13 38 38" src="https://github.com/user-attachments/assets/1434107d-a90e-4ed1-8bea-1ec0dd0ac51e">

**Comment by zionnite** [comment]
is it possible to just get the value click on, without get the instances like this `[Instance of 'ColorDatum']`
??

**Comment by zionnite** [comment]
> @zionnite hello fella, thanks for using the library <3 I'll look into it and get back at you !

your package is the most outstanding amongst the all I search for in `pub.dev`,
I love how you make it flexible for dev to customize their widget they choose to use and it is simple and straightforward

**Comment by esentis** [comment]
> is it possible to just get the value click on, without get the instances like this `[Instance of 'ColorDatum']`
> ??

Hmm can you elaborate a bit on this, I don't think I have grasped what you mean :<

**Comment by zionnite** [comment]
hello, I'm very grateful for your support in resolving this issues,
the other stuff I mentioned it's not actually a big deal

**Comment by zionnite** [comment]
nice working with you today
