### ISSUE TITLE
Display list items only when list is clicked

### ISSUE THREAD

**Issue by bubnenkoff** [esentis/multiple_search_selection#6]
Now I at start we see dropdown list, but I would like to show it only when there was click on input for picking elements

**Comment by esentis** [comment]
Hello there and thanks for taking the time to fill the issue. 

Let's see if I get it directly, you want the list (of which you pick the items) to not be visible until you have typed something in the search field ?

**Comment by bubnenkoff** [comment]
By default I am seeing items for picking. List of them is open. I would like to get it works as classical dropdown menu with muliselect. So before getting all list user should click on dropdown menu.

**Comment by esentis** [comment]
Ok I think I understood.

Thing is, the list was not meant to work as a dropdown. I don't know how the search would work with a dropdown implementation. 

I will leave this open and will look into it soon.

**Comment by umangsh** [comment]
A possible way this can work is:

1. Initialize widget with initialPickedItems, display ONLY the textformfield with pickeditemchips. Search bar + items scroll container is hidden. _MultipleSearchSelectionState.expanded seems related but isn't used as far as I can tell: https://github.com/esentis/multiple_search_selection/blob/develop/lib/multiple_search_selection.dart#L465
 
2. Add a dropdown toggle that can toggle display for the search + items container (See image). onTap outside the dropdown hides it.
<img width="303" alt="Screen Shot 2022-06-28 at 10 31 01 AM" src="https://user-images.githubusercontent.com/31483143/176246173-a46e21c9-57f1-4a2a-be32-66a378ebc22a.png">

Hope this is helpful!

**Comment by esentis** [comment]
Awesome, thanks for the tips !

**Comment by umangsh** [comment]
No problem. It's a great plugin, thanks for being open to feature requests!
