### ISSUE TITLE
Object selection options

### ISSUE THREAD

**Issue by umangsh** [esentis/multiple_search_selection#7]
## Describe the feature you'd like

1. Is it possible to select custom objects other than String in the dropdown? Often choices will have an ID for form processing and a String for display:

items: MyObj (id: ..., name: ..., toString() => name)

2. Support for async data fetch for populating items instead of expecting all items available up front. Even better if the data fetch is paginated.

**Comment by esentis** [comment]
Hello there😊 I really like your suggestions, I'll look into it the coming week, and make it happen (hopefully).

**Comment by umangsh** [comment]
Hi, just checking in. Were you able to look at this feature request?

**Comment by esentis** [comment]
> Hi, just checking in. Were you able to look at this feature request?

Hello there, yes I have looked into it briefly but haven't found the time I wanted to implement & refactor the code. 

Unfortunately, I can't give you an ETA right now. 
Of course every PR is welcome 🙏

**Comment by umangsh** [comment]
No worries 🤞.
I'm new to Flutter - too early to contribute useful PRs unfortunately.
